"""Add pay schedule anchor date

Revision ID: 209d7649614a
Revises: a7ab934bd417
Create Date: 2026-01-06 11:19:16.861466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209d7649614a'
down_revision = 'a7ab934bd417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_payday', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pay_schedule')
    # ### end Alembic commands ###
