"""Add paid_through to bills

Revision ID: 891e4f236df1
Revises: c24dc91ed0e8
Create Date: 2026-01-02 19:26:08.532201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891e4f236df1'
down_revision = 'c24dc91ed0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_through', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('paid_through')

    # ### end Alembic commands ###
