"""Expenses: add duplicate flags and fingerprint

Revision ID: a7ab934bd417
Revises: d9d70703a670
Create Date: 2026-01-05 15:47:39.939107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ab934bd417'
down_revision = 'd9d70703a670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_duplicate', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expense_fingerprint'), ['fingerprint'], unique=False)
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expense_fingerprint'))
        batch_op.drop_column('duplicate_of_id')
        batch_op.drop_column('is_duplicate')
        batch_op.drop_column('fingerprint')

    # ### end Alembic commands ###
